// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpzhincrxgxyyzulmrzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwemhpbmNyeGd4eXl6dWxtcnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzEwMzIsImV4cCI6MjA2MTg0NzAzMn0.GVGaY2AKcT7nFxRxugOKm7NocgYvnFmtV32SmpVip-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);