// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdutodrbvozfdnuqkshc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdXRvZHJidm96ZmRudXFrc2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzkxMDYsImV4cCI6MjA2MTkxNTEwNn0.vq-QytO39hrRw2aDUx4YVmevJ36dJrQOHTdstC2ZI1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);